#!/usr/bin/perl -w
# This script creates the symlinks needed by this RPM
# Specific support exists to create symlinks within e-smith web "panels"
# and for links from named "events" directories into the "actions" directory

use esmith::Build::CreateLinks qw(:all);

# Links for the panel
panel_link("servicecontrol", "manager");



#sub event_link
#{
#    my ($action, $event, $level) = @_;
#
#    unlink "root/etc/e-smith/events/${event}/S${level}${action}";
#    symlink("../actions/${action}",
#	"root/etc/e-smith/events/${event}/S${level}${action}")
#    or die "Can't symlink to " .
#	"root/etc/e-smith/events/${event}/S${level}${action}: $!";
#}


#--------------------------------------------------
##service2adjust
#--------------------------------------------------
foreach my $event (qw( service-access 
                        service-one))
    {
    safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/httpd-e-smith");
    safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/httpd-admin");
    safe_symlink("adjust", "root/etc/e-smith/events/$event/services2adjust/masq");
    safe_symlink("condrestart", "root/etc/e-smith/events/$event/services2adjust/pptpd");
    safe_symlink("sighup", "root/etc/e-smith/events/$event/services2adjust/qmail");
    safe_symlink("sigterm", "root/etc/e-smith/events/$event/services2adjust/radiusd");
    safe_symlink("sighup", "root/etc/e-smith/events/$event/services2adjust/sshd");
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/wan");
    }
#    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/qpsmtpd");
#    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/sqpsmtpd");
#    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/pop3");
#    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/pop3s");   
#    safe_symlink("reload", "root/etc/e-smith/events/$event/services2adjust/dovecot");   
#    safe_symlink("force-reload", "root/etc/e-smith/events/$event/services2adjust/squid");   
#    safe_symlink("sigterm", "root/etc/e-smith/events/$event/services2adjust/dnscache");  

#}


#-------------------------------------------------
##Action2events
#-------------------------------------------------

foreach my $event (qw ( service-access
                        service-one))
        {
            event_link("update-ifcfg", $event, "10");
            event_link("service-control", $event, "90");
        }


#--------------------------------------------------
# functions for manager panel
#--------------------------------------------------
my $panel = "manager";

#panel_link("function1", $panel);
#panel_link("function2", $panel);

#--------------------------------------------------
# actions for console-save event:
#--------------------------------------------------
$event = "console-save";

#event_link("action1", $event, "55");
#event_link("action2", $event, "60");

#--------------------------------------------------
# actions for domain-create event:
#--------------------------------------------------
$event = "domain-create";

#event_link("action1", $event, "55");
#event_link("action2", $event, "90");

