#!/usr/bin/perl -wT
# vim: ft=xml ts=8 sw=4 noet:
#----------------------------------------------------------------------
# heading     : Configuration
# description : Service Control
# navigation  : 6000 6810
#----------------------------------------------------------------------
#----------------------------------------------------------------------
# copyright (C) 2004 Schirrm's Studio
# copyright (C) 2002 Mitel Networks Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------

use strict;
use esmith::FormMagick::Panel::servicecontrol;
my $form = esmith::FormMagick::Panel::servicecontrol->new();
# Uncomment the next line for debugging purposes.
# $form->debug(1);
$form->display();


__DATA__
<form
    title="FORM_TITLE"
    header="/etc/e-smith/web/common/head.tmpl"
    footer="/etc/e-smith/web/common/foot.tmpl">

    <!-- page 0 -->
    <page
        name="First"
        pre-event="print_status_message()"
        post-event="main()">
        <description>FIRST_PAGE_DESCRIPTION</description>
        <subroutine src="displayNavig()" />
    </page>

    <page
        name="ServiceActivate"
        pre-event="print_status_message()"
        post-event="main()">
        <description>FIRST_PAGE_DESCRIPTION</description>
        <subroutine src="displayService()" />
    </page>
    <page
        name="ServiceConfirm"
        pre-event="turn_off_buttons"
        post-event="main()">
        <subroutine src="displayConfirmActivate()" />
    </page>

    <page
        name="TCPPORTEdit"
        pre-event="print_status_message()"
        post-event="main()">
        <description>FIRST_PAGE_DESCRIPTION</description>
        <subroutine src="displayServiceTcp()" />
    </page>
    <page
        name="TCPConfirm"
        pre-event="turn_off_buttons"
        post-event="main()">
        <subroutine src="displayConfirmTCP()" />
    </page>

    <page
        name="ServiceAccess"
        pre-event="print_status_message()"
        post-event="main()">
        <description>FIRST_PAGE_DESCRIPTION</description>
        <subroutine src="displayServiceAccess()" />
    </page>
    <page
        name="ServiceAccessConfirm"
        pre-event="turn_off_buttons"
        post-event="main()">
        <subroutine src="displayConfirmAccess()" />
    </page>

</form>
